apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  apps: sshd

resources:
- deployment.yaml
- service.yaml
- ingressroute.yaml

configMapGenerator:
- files:
  - authorized_keys
  name: authorized-keys
